### ISSUE TITLE
Main File Refactoring

### ISSUE THREAD

**Issue by monoai** [monoai/GDPHYSX_06#11]
Main file is jam-packed with variables, declarations, and sometimes simple workarounds due to the fact that the program only mostly uses the main function, it would probably look better and might even be structured better if the main file is restructured in a way that it wouldn't be limited on just using the main function, especially if we would get to the point that we might need to re-use or reconstruct some structure of the code (like possibly doing the particle world code). 
This issue isn't extremely necessary but it would probably look better and be helpful sometime in the future, both for the project and for improving coding standards.

---

### To-do list (Suggestions?)
- [x] Create a main.hpp header file
- [x] Move global variables, misc. declarations, and other refactorable factors in the header file
- [x] Refactor key/mouse input so that it wouldn't need a bool variable anymore, and that we could easily add new inputs in the future
- [ ] Remove some unused lines of codes (Shader Loading, unused matrices, etc.)
- [x] Remove some unused headers (I think ctime isn't used anymore, please double check)
- [x] Find a way to be able to separate initializing objects and leaving objects inside a loop (dont have to initialize an object inside the while loop) [NOTE: Already solved via particle world?]
- [ ] Using typedef to shorten long declarations like `std::vector<std::unique_ptr<TYPE>>` so that it'll look neater and probably lessens possible confusion (Argument, typedef makes it more confusing unless someone looks at the original definition)
