### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by monoai** [monoai/GDPHYSX_06#6]
There's a few things that could be refactored to make our lives better. Here's the current list for those:

---
### To-do list:
- [x] ObjData stored inside the particle instead of passing every time draw is called.
- [x] Upgrading semi-fixed timestep to variable step
- [x] Float variables that are overloading/writing double variables should use double instead.
